### PR TITLE
The Final Merge of CSE312. Thanks everyone!

### PR DESCRIPTION
**Pull request by Trinooo**

### CODE REVIEW

**Comment by srcalo** [comment]
slay

**Review by srcalo — APPROVED** [review]
I'm not looking at 32740 files screw that. ✨Slay the day away✨

**Comment by ahanabhattchrya** [comment]
Looks good!!

**Review by ahanabhattchrya — APPROVED** [review]
SLAYY

**Comment by Trinooo** [comment]
A great semester!

**Comment by srcalo** [comment]
> 

Idk about that one but sure /s

**Pull request merged**
